#!/bin/bash

source $cwd/consts
source $cwd/helpers
while true
do
	ip=$(host myip.opendns.com resolver1.opendns.com | grep "has address" | cut -d " " -f 4)
	if is_ip $ip
	then
		public_ip=$ip
		break
	fi
done
