#!/bin/bash

home_directory=$(cd "$(dirname $0)" &> /dev/null && pwd)
directories=(config distro service)
cwd="$home_directory/require"
source $cwd/run
cwd="$home_directory/checkup"
source $cwd/run

for directory in ${directories[*]}
do
    print_centered " ${directory^} Directory " "#"
    cwd="$home_directory/$directory"
    is_file_execute "$cwd/run"
done
exit
