#!/bin/bash

while true
do
    read -p "Do you want add host(yes/no): " add_host
    if [ $add_host = "yes" ]
    then
        read -p "What's your host name(example.com): " host
        host=${host:-"example.com"}
        if [ -f $apache_directory/sites-available/${host}.conf ]
        then
            message "${danger_color}Host ${host} already exists!!!$default_color"
            read -p "Do you want replace this(yes/no): " replace_host
            if [ $replace_host != "yes" ]
            then
                continue
            fi
        fi
        mkdir -p /var/www/$host/html
        mkdir -p /var/www/$host/logs
        echo "<marquee>$host</marquee>" > /var/www/$host/html/index.html
        sed "s:example.com:$host:g" $cwd/$service/virtualhost.conf | tee $apache_directory/sites-available/${host}.conf &>/dev/null
        read -p "Do you want enable ssl(yes/no): " enable_ssl
        if [ $enable_ssl = "yes" ]
        then
            openssl req -newkey rsa:4096 \
            -x509 \
            -sha256 \
            -days 3650 \
            -nodes \
            -out $ssl_directory/${host}.crt \
            -keyout $ssl_directory/${host}.key
            sed "s:example.com:$host:g; s:/etc/apache2/ssl:$ssl_directory:g" $cwd/$service/ssl_virtualhost.conf | tee -a $apache_directory/sites-available/${host}.conf &>/dev/null
            sed -i "4i Redirect / https://$host/" $apache_directory/sites-available/${host}.conf
        fi
        a2ensite ${host}.conf
    else
        break
    fi
done
systemctl restart apache2