#!/bin/bash

services=(ssh dns web)
user_services=()
for service in ${services[*]}
do
    read -p "Do you want install ${service^^} service(yes/no): " answer
    if [ ${answer:-"no"} = "yes" ]
    then
        cwd="$home_directory/service"
        user_services+=($service)
        print_centered " ${service^^} Service " "*"
        is_file_execute "$cwd/$service/run"
    fi
    answer=''
done
