#!/bin/bash

debian_distros=(debian ubuntu)
redhat_distros=(centos rhel fedora)
permited_distros=(${debian_distros[*]} ${redhat_distros[*]})

distro=$(grep -w ID /etc/os-release | cut -d = -f 2)
if echo ${permited_distros[*]} | grep -vq $distro
then
	message "${danger_color}This linux distro is not supported${default_color}"
	exit
fi
if echo ${debian_distros[*]} | grep -q $distro
then
	distro="debian"
else
	distro="redhat"
fi
