#!/bin/bash

checkups=(permission distro connection)
print_centered " Checkup Directory " "#"
for checkup in ${checkups[*]}
do
    print_centered " ${checkup^} Checkup " "*"
    is_file_execute "$cwd/$checkup"
done
